FROM node:20-alpine
WORKDIR /app

COPY .docker/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

COPY . .
RUN npm ci
RUN chown -R node:node /app

EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]

ENTRYPOINT ["entrypoint.sh"]